server:
  context-path: /movie
  port: 9001
spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/,http://peer2:8882/eureka/,http://peer1:8881/eureka/,http://peer3:8883/eureka/
  instance:
    prefer-ip-address: true
    # eureka 显示ip和端口的配置
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#微服务 restTemplate url 配置
user:
  userServerUrl: http://localhost:8002/
#微服务 restTemplate url 配置
userRibbon:
  userServerName: http://microservice-provider-user/

# feign 日志打印设置
feign:
  client:
    config:
      microservice-provider-user:
        loggerLevel: full
logging:
  level:
    org.example.feign.UserFeignClient: debug

