server:
  port: 9001
spring:
  application:
    name: microservice-getaway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8882/eureka/,http://peer1:8881/eureka/,http://peer3:8883/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
management:
  security:
    enabled: false
#多个服务路由配置
zuul:
  prefix: /api
  strip-prefix: false
  routes:
    user-route:
      service-id: microservice-provider-user
      path: /user/**
    movie-route:
      service-id: microservice-consumer-movie
      path: /movie/**
  max:
     host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: true

#ribbon
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

#hystrix
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

logging:
  level:
    com.netflix: debug

